#!/bin/sh

MAXCOUNT=68 
count=16

while [ "$count" -le $MAXCOUNT ]
do
	echo chiba0$count
        ssh -oStrictHostKeyChecking=no chiba0$count killall java
        let "count += 1"
done

MAXCOUNT=157
count=100

while [ "$count" -le $MAXCOUNT ]
do
	echo chiba$count
        ssh -oStrictHostKeyChecking=no chiba$count killall java
        let "count += 1"
done

MAXCOUNT=9
count=1

while [ "$count" -le $MAXCOUNT ]     
do
	echo chiba00$count
	ssh -oStrictHostKeyChecking=no chiba00$count killall java
	let "count += 1"
done

